config/routes.rb
Rails.application.routes.draw do
  resources :books
  root :to => redirect('/books')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base

  def self.all_genres
    ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']
  end

  validates :title, :presence => true
  validates :publish_date, :presence => true
  validates :genre, :inclusion => {:in => Book.all_genres}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    sort = params[:sort] #|| session[:sort]

    case sort
      when 'title'
        ordering,@title_header = {:title => :asc}, 'hilite'
      when 'publish_date'
        ordering,@date_header = {:publish_date => :asc}, 'hilite'
    end

    @all_genres = Book.all_genres
    @selected_genres = params[:genres] || {} #begin|| session[:genres] || {}
    if @selected_genres == {}
      @selected_genres = Hash[@all_genres.map{|genre| [genre, genre]}]
    # end

    # if params[:sort] != session[:sort] or params[:genres] != session[:genres]
    # session[:sort] = sort
    # redirect_to :sort => sort, :genres => @selected_genres and return
    end

    @books = Book.where(genre: @selected_genres.keys).order(ordering)

  end

  def show
    id = params[:id]
    @book = Book.find(id)
  end

  def new
    @book = Book.new
  end

  def create
    params.require(:book)
    permitted = params[:book].permit(:title,:genre,:publish_date,:isbn_number,:description,:author)
    @book = Book.new(permitted)
    if @book.save
      flash[:notice] = "#{@book.title} was successfully created."
      redirect_to books_path
    else
      render 'new'
    end

  end

  def edit
    @book = Book.find params[:id]
  end

  def update
    @book = Book.find params[:id]
    params.require(:book)
    permitted = params[:book].permit(:title,:genre,:publish_date,:isbn_number,:description,:author)
    if @book.update_attributes  (permitted)
      flash[:notice] = "#{@book.title} was successfully updated."
      redirect_to book_path(@book)
    else
      render 'edit'
    end

  end

  def destroy
    @book = Book.find params[:id]
    @book.destroy
    flash[:notice] = "Book '#{@book.title}' deleted."
    redirect_to books_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.haml
%h2 Edit Book

<hr />
= link_to 'Book details', book_path(@book)
= link_to 'Back to books', books_path
<hr />

= form_tag book_path(@book), :method => :put do

  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error

  = label :book, :title, 'Title'
  = text_field :book, :title

  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']

  = label :book, :publish_date, 'Released On'
  = date_select :book, :publish_date

  = label :book, :isbn_number, 'ISBN'
  = text_field :book, :isbn_number

  = label :book, :author, 'Author'
  = text_field :book, :author

  = label :book, :description, 'Description'
  = text_field :book, :description

  <br/>
  = submit_tag 'Save Changes'

app/views/books/index.html.haml
%h1 All Books

<hr/>
= link_to 'Add book', new_book_path
= link_to 'View all books', books_path
<hr />

= form_tag books_path, :method => :get do
  %b Genres:
  - @all_genres.each do |genre|
    = check_box_tag "genres[#{genre}]"
    = genre
  = submit_tag 'Selected only'

<hr/>
%table#books
  %thead
    %tr
      %th Id
      %th{:class => @title_header}= link_to 'Title', books_path(:sort => 'title'), :id => 'title_header'
      %th Genre
      %th ISBN
      %th{:class => @date_header}= link_to 'Publish Date', books_path(:sort => 'publish_date'), :id => 'publish_date_header'
      %th Details
      %th Edit
      %th Delete
  %tbody
    - @books.each do |book|
      %tr
        %td= book.id
        %td= book.title
        %td= book.genre
        %td= book.isbn_number
        %td= book.publish_date.strftime("%B %d, %Y")
        %td= link_to "Details", book_path(book)
        %td= link_to "Edit", edit_book_path(book)
        %td= link_to "Delete", book_path(book), :method => :delete

app/views/books/new.html.haml
%h2 Create New Book
<hr />
= link_to 'Back', books_path
<hr />
= form_tag books_path, :method => :post do

  - unless @book.errors.empty?
    #warning
      Errors prevented this book from being #{controller.action_name}d:
      %ul
        - @book.errors.full_messages.each do |error|
          %li= error

  = label :book, :title, 'Title'
  = text_field :book, :title

  = label :book, :genre, 'Genre'
  = select :book, :genre, ['Science fiction','Drama','Action and Adventure','Romance','Mystery','Horror']

  = label :book, :publish_date, 'Released On'
  = date_select :book, :publish_date

  = label :book, :isbn_number, 'ISBN'
  = text_field :book, :isbn_number

  = label :book, :description, 'Description'
  = text_field :book, :description

  <br/>
  = submit_tag 'Save Changes'

app/views/books/show.html.haml
%h2 Details about #{@book.title}
<hr />
= link_to 'Back to books', books_path
= link_to 'Edit book', edit_book_path(@book)
= link_to 'Delete book', book_path(@book), :method => :delete
<hr />
%ul#details
  %li
    Genre:
    = @book.genre
  %li
    Publish Date:
    = @book.publish_date.strftime("%B %d, %Y")

  %li
    ISBN:
    = @book.isbn_number

  %h3 Description:
  %p#description= @book.description

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %link{ :href => image_path('favicon.ico'), :rel => 'icon', :type => 'image/x-icon' }
    %title Favourite Books!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]

    #main
      = yield